# https://docs.gitlab.com/runner/executors/docker.html
# https://docs.gitlab.com/runner/configuration/advanced-configuration.html#volumes-in-the-runnersdocker-section
concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800
[[runners]]
  name = "ip-172-31-33-166-docker"
  url = "https://ci.domain.com/gitlab/"
  token = "xxxxxxxxxx"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:dind"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache", "/home/gitlab-runner/.ssh:/root/.ssh:ro"]
    shm_size = 0
