image: busybox:latest

stages:
  - build
  - test
  - deploy
  - destroy

before_script:
  - echo "Before script section"

after_script:
  - echo "After script section"

build1:
  stage: build
  script:
    - echo "building"

test1:
  stage: test
  script:
    - echo "testing"

test2:
  stage: test
  script:
    - echo "parallel test"

deploy1:
  stage: deploy
  script:
    - echo "deploying"
    - deploytime=$(( ( RANDOM % 10 )  + 1 ))
    - sleep $deploytime

destroy:
  stage: destroy
  when: manual
  script: 
    - echo "destroy --dry-run"

destroy-confirmation:
  stage: destroy
  script: echo "destroy --force"
  when: manual
  needs:
    - destroy
