apiVersion: batch/v1
kind: CronJob
metadata:
  name: minutely-job
  namespace: default
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo "hi from $(hostname)"
          restartPolicy: OnFailure
