---
# kubectl create secret generic app-secret --from-literal=username=admin --from-literal=password=admin --dry-run=client --output=yaml
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  username: YWRtaW4= # base64 encoded value of "admin"
  password: YWRtaW4= # base64 encoded value of "admin"
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: container
    image: busybox:latest
    volumeMounts:
    - name: secret-volume
      mountPath: "/etc/secret"
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: app-secret
