version: "3.7"

services:
  redis-server:
    image: redis:7.0
    container_name: redis-server
    environment:
      - DOCKERHUB_DOCS=https://hub.docker.com/_/redis
    networks:
      - app
    ports:
      - 6379:6379
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

networks:
  app:
    name: app